[package]
name = "manager"
version = "1.0.0"
authors = ["Anubhav Jain"]

[dependencies.AptosFramework]
git = "https://github.com/aptos-labs/aptos-framework.git"
rev = "aptos-release-v1.29"
subdir = "aptos-framework"